/* empty css                      */import{S as c,N as l,K as d,A as u}from"./assets/vendor-BcDFKbXm.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();c.use([l,d]);new c(".swiper-ingame",{slidesPerView:1,spaceBetween:24,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".arrow-right",prevEl:".arrow-left"},a11y:!0,breakpoints:{1200:{slidesPerView:2.5}}});const f=document.getElementById("videoPreviewWrapper"),a=document.getElementById("videoWrapper");a.innerHTML;f.addEventListener("click",()=>{a.innerHTML=`
    <iframe
    width="100%" 
    src="https://www.youtube.com/embed/Wwge92GWJds?autoplay=1"
    frameborder="0"
     allow="autoplay; encrypted-media"
        allowfullscreen>
      </iframe>
    `});const m=new u("#faq-accordion-container",{duration:500,elementClass:"faq-item",triggerClass:"faq-button",panelClass:"faq-text-container"});m.open(0);const p=document.querySelector(".battle-girl"),y=document.querySelector("#battle"),w=document.querySelector(".battle-boy"),b=new IntersectionObserver((s,r)=>{s.forEach(o=>{o.isIntersecting&&(p.classList.add("visible"),setTimeout(()=>{w.classList.add("visible")},1200),r.disconnect())})},{threshold:.3});b.observe(y);const g=document.querySelectorAll(".rewivse-item"),v=document.querySelector("#reviwes"),h=new IntersectionObserver((s,r)=>{s.forEach(o=>{o.isIntersecting&&(g.forEach((i,e)=>{setTimeout(()=>{i.classList.add("visible")},e*200)}),r.disconnect())})},{threshold:.3});h.observe(v);
//# sourceMappingURL=index.js.map
